### PR TITLE
Some little improvements from end of August

### PR DESCRIPTION
**Pull request by tinchodias**
The PR rebases part of https://github.com/Ducasse/Myg/pull/5

### CODE REVIEW

**Comment by tinchodias** [comment]
@Ducasse apart from little code improvements (IMHO), in fact the commit about explosion improves the visual effect. Without this change, the stars hide below tiles along their movement

**Comment by tinchodias** [comment]
I tried loading latest changes in Bloc:master and Toplo:master and these seem to work well:
```
MineSweeper open.
Takuzu open.
Sokoban open.
```
Steps to load were in P11, load with following script, then repair Bloc and Toplo in Iceberg, then had to manually recompile 2 methods that had some instvar wrongly bound, and the 3 demos worked.
```
Metacello new
 baseline: 'Myg';
 repository: 'github://Ducasse/Myg:martinPassRecovery/src';
 onConflictUseIncoming;
 load.
```

I will try without upgrading Toplo and Bloc now.

**Comment by tinchodias** [comment]
I tried with the fixed version of Toplo that the baseline of Myg loads and I get this error while opening any of the demos: "Error: Explicitly required method".

I see that Toplo commit is from beginnings of August, and my changes were done several weeks later. Alain is pushing the disruptive changes on a separate Toplo branch.

**Comment by Ducasse** [comment]
Ok I merge now for us this is important that the students can get a fixed version of Toplo, Myg and Bloc.

**Pull request merged**
